// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlqlpxmmyoovwtgnuuot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhscWxweG1teW9vdnd0Z251dW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTM0NDcsImV4cCI6MjA3Mzg2OTQ0N30.SWetej1suqhZfjce05RV10X08V-JVZ1G_WXfqzhgalw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});